---

- fail: msg="Cannot use freeipa if there is no master set"
  when: freeipa_master is not defined

- fail: msg="Cannot use freeipa role if there is no kerberos admin password set"
  when: kerberos_admin_password is not defined

- fail: msg="Cannot use freeipa if there is no ldap admin password set"
  when: directory_admin_password is not defined

## we don't use the client portion of the role
# - include: client.yml
#   when: ansible_fqdn != freeipa_master and ansible_fqdn not in freeipa_replicas

- include: server.yml
  when: inventory_hostname == freeipa_master or inventory_hostname in freeipa_replicas
