---

- name: Install packages for the server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ipa-server
    - ipa-server-dns
  become: true

- include: master.yml
  when: inventory_hostname == freeipa_master

- include: replica.yml
  when: inventory_hostname in freeipa_replicas

- include: ssl.yml
  become: true
  when: vault_mellon_ssl_crt is defined
